#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save

ZSH=/home/greg/.zgen/robbyrussell/oh-my-zsh-master

#
source "/home/greg/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.plugin.zsh"
source "/home/greg/.zgen/hchbaw/opp.zsh-master/opp.plugin.zsh"
source "/home/greg/.zgen/willghatch/zsh-cdr-master/cdr.plugin.zsh"
source "/home/greg/.zgen/zsh-users/zaw-master/zaw.plugin.zsh"
source "/home/greg/.zgen/willghatch/zsh-saneopt-master/saneopt.plugin.zsh"
source "/home/greg/.zgen/willghatch/zsh-hooks-master/zsh-hooks.plugin.zsh"
source "/home/greg/.zgen/termoshtt/zaw-systemd-master/zaw-systemd.plugin.zsh"
source "/home/greg/.zgen/https-COLON--SLASH--SLASH-github.com-SLASH-nojhan/liquidprompt-master/liquidprompt.plugin.zsh"
source "/home/greg/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/home/greg/.zgen/zsh-users/zsh-history-substring-search-master /home/greg/.zgen/hchbaw/opp.zsh-master /home/greg/.zgen/willghatch/zsh-cdr-master /home/greg/.zgen/zsh-users/zaw-master /home/greg/.zgen/willghatch/zsh-saneopt-master /home/greg/.zgen/willghatch/zsh-hooks-master /home/greg/.zgen/termoshtt/zaw-systemd-master /home/greg/.zgen/https-COLON--SLASH--SLASH-github.com-SLASH-nojhan/liquidprompt-master /home/greg/.zgen/zsh-users/zsh-completions-master/src /home/greg/.zgen/zsh-users/zsh-syntax-highlighting-master ${fpath})
